entryPoints:
  http:
    address: ":80"

http:
  routers:
    http-catchall:
      rule: hostregexp(`{host:.+}`)
      entrypoints:
      - http

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
